server:
    port: 8080
    servlet:
        jsp:
            init-parameters:
                development: true
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/babel?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
