server:
    port: 8080
    servlet:
        jsp:
            init-parameters:
                development: true
spring:
    datasource:
        url: jdbc:mysql://61.109.236.108:3306/travelcheck?useSSL=false&serverTimezone=UTC
        username: minwoo
        password: 780525
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        view:
            prefix: /resources/templates/
            suffix: .html

kakao:
    client_id: 82f2d73a40b55b4b5854f06ed5d1e436
    redirect_uri: http://localhost:8080/login/oauth2/code/kakao
    client_secret: tioEnkqyf3opfp51drI8FYN4nUbYOb1u

#mybatis
mybatis:
    #mapper-locations: classpath:/mappers/*.xml
    type-aliases-package: com.aitok.travelcheck.test.dto;