server:
    port: 8080
    servlet:
        jsp:
            init-parameters:
                development: true
spring:
    datasource:
        url: jdbc:mysql://61.109.236.108:3306/travelcheck?useSSL=false&serverTimezone=UTC
        username: minwoo
        password: 780525
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        view:
            prefix: /resources/templates/
            suffix: .html
    jpa:
        hibernate:
            ddl-auto: none  # or 'create', 'validate', 'create-drop' as needed
        properties:
            hibernate:
                show_sql: true
                format_sql: true

kakao:
    client_id: 82f2d73a40b55b4b5854f06ed5d1e436
    redirect_uri: http://61.109.236.108:8080
    #redirect_uri: http://localhost:8080
    client_secret: tioEnkqyf3opfp51drI8FYN4nUbYOb1u

springdoc:
    api-docs:
        path: /api-docs
        groups.enabled: true
    swagger-ui:
        path: /swagger-ui-custom.html
        enabled: true
        groups-order: ASC
        tags-sorter: alpha
        operations-sorter: alpha
        display-request-duration: true
        doc-expansion: none
    cache:
        disabled: true
    model-and-view-allowed: true
